<?php

// SLIDER SECTION
function eeco_section_slider($data) {
    $data['fields'][0]['layouts'][] = array(
        'key' => 'group_hero_slider',
        'name' => 'hero_slider',
        'label' => __('Slider', 'bgh-theme-child'),
        'display' => 'block',
        'sub_fields' => array(
            array(
                'key' => 'field_slider_content_analytics',
                'label' => 'Sisältö & Analytiikka',
                'name' => '',
                'type' => 'accordion',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_slider_repeater',
                'label' => __('Slides', 'bgh-theme-child'),
                'name' => 'slider_repeater',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => __('Add new slide', 'bgh-theme-child'),
                'sub_fields' => array(
                    array(
                        'key' => 'field_slide_image',
                        'label' => 'Image, desktop',
                        'name' => 'slide_desktop',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_slide_image_mobile',
                        'label' => 'Image, mobile',
                        'name' => 'slide_mobile',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_slide_text_1',
                        'label' => 'Sliden tekstit',
                        'name' => 'slide_text_1',
                        'type' => 'text',
                        'instructions' => 'Kirjoita tekstit, jotka näkyvät kuvan päällä. Jokainen tekstilaatikko on oma rivinsä. Max 50 merkkiä / rivi.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '50',
                    ),
                    array(
                        'key' => 'field_slide_text_2',
                        'label' => 'Sliden tekstit',
                        'name' => 'slide_text_2',
                        'type' => 'text',
                        'instructions' => 'Kirjoita tekstit, jotka näkyvät kuvan päällä. Jokainen tekstilaatikko on oma rivinsä. Max 50 merkkiä / rivi.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '50',
                    ),
                    array(
                        'key' => 'field_slide_text_3',
                        'label' => 'Sliden tekstit',
                        'name' => 'slide_text_3',
                        'type' => 'text',
                        'instructions' => 'Kirjoita tekstit, jotka näkyvät kuvan päällä. Jokainen tekstilaatikko on oma rivinsä. Max 50 merkkiä / rivi.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '50',
                    ),
                    array(
                        'key' => 'field_slide_cta',
                        'label' => 'Call-To-Action',
                        'name' => 'slide_cta',
                        'type' => 'link',
                        'instructions' => 'Kirjoita Call-to-Action teksti sekä osoite, johon linkin klikkaaminen johtaa. Jättämällä tyhjäksi, slidessä ei näytetä CTA:ta.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                    ),
                ),
            ),
            array(
                'key' => 'field_slide_styles',
                'label' => 'Tyylittely',
                'name' => '',
                'type' => 'accordion',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_slide_time',
                'label' => 'Kuinka pitkään yksi slide on näkyvissä?',
                'name' => 'slide_time',
                'type' => 'number',
                'instructions' => 'Lisää aika sekunteina, oletuksena käytetään 4 sekuntia.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'step' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_slide_layer',
                'label' => 'Läpikuultava layer taustakuvan päälle',
                'name' => 'slide_layer',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_slide_layer_color',
                'label' => 'Tumma vai vaalea layer?',
                'name' => 'slide_layer_color',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_slide_layer',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'dark' => 'Tumma',
                    'light' => 'Vaalea',
                ),
                'default_value' => array(
                    0 => 'dark',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_slide_section_width',
                'label' => 'Osion leveys',
                'name' => 'slide_section_width',
                'type' => 'select',
                'instructions' => 'Kuinka leveä tämä osio on. Vaikuttaa kuvan leveyteen.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'container' => 'Normaali',
                    'container-fluid' => 'Leveä',
                    'full-width' => 'Koko näyttö',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_slide_content_align',
                'label' => 'Sisällön tasaus',
                'name' => 'slide_content_align',
                'type' => 'select',
                'instructions' => 'Onko teksti keskitettynä sliden keskelle vai tasataanko se jompaan kumpaan reunaan.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'center' => 'Keskitetty',
                    'left' => 'Vasen',
                    'right' => 'Oikea',
                ),
                'default_value' => array(
                    0 => 'center',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_slide_font_color',
                'label' => 'Tekstin väri',
                'name' => 'slide_font_color',
                'type' => 'select',
                'instructions' => 'Valitse millä värillä teksti näkyy sliden päällä.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'primary-font' => 'Fontin väri #1',
                    'secondary-font' => 'Fontin väri #2',
                    'tertiary-font' => 'Fontin väri #3',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_slide_cta_style',
                'label' => 'CTA-tyylit',
                'name' => 'slide_cta_style',
                'type' => 'select',
                'instructions' => 'Valitse miltä CTA-nappi näyttää.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'primary-cta' => 'CTA 1',
                    'secondary-cta' => 'CTA 2',
                    'text-link' => 'Tekstilinkki',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_slide_cta_style_2',
                'label' => 'CTA 2-tyylit',
                'name' => 'slide_cta_style_2',
                'type' => 'select',
                'instructions' => 'Valitse miltä CTA 2-nappi näyttää.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'primary-cta' => 'CTA 1',
                    'secondary-cta' => 'CTA 2',
                    'text-link' => 'Tekstilinkki',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_slide_text_box',
                'label' => 'Taustaväri / taustalaatikko tekstille',
                'name' => 'slide_text_box',
                'type' => 'true_false',
                'instructions' => 'Lisätäänkö tekstisi alle taustavärilaatikko? Tämän avulla teksti erottuu helpommin taustakuvasta.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_slide_text_box_color',
                'label' => 'Taustavärilaatikon väri',
                'name' => 'slide_text_box_color',
                'type' => 'select',
                'instructions' => 'Valitse väri, joka tulee tekstisi alle.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_slide_text_box',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'primary-bg' => 'Taustaväri #1',
                    'secondary-bg' => 'Taustaväri #2',
                    'tertiary-bg' => 'Taustaväri #3',
                    'quatenary-bg' => 'Taustaväri #4',
                    'quinary-bg' => 'Taustaväri #5',
                    'senary-bg' => 'Taustaväri #6',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_slide_developer',
                'label' => 'Developer',
                'name' => '',
                'type' => 'accordion',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_slide_class',
                'label' => 'CSS-class',
                'name' => 'slide_class',
                'type' => 'text',
                'instructions' => 'Lisää osiolle class-attribuutti',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_slide_id',
                'label' => 'ID',
                'name' => 'slide_id',
                'type' => 'text',
                'instructions' => 'Lisää osiolle uniikki ID',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
    );
    return $data;
}
add_filter('bgh_acf_default_template', 'eeco_section_slider', 10, 2);